//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicaCliente
{
    using Newtonsoft.Json.Linq;
    using System;
    using System.Collections.Generic;
    
    public class ARTISTA
    {
        public ARTISTA()
        {

        }

        public ARTISTA(string txtJson)
        {
            JObject objeto = JObject.Parse(txtJson);
            ART_ID = (string)objeto["ART_ID"];
            ART_NOMBRE = (string)objeto["ART_NOMBRE"];
            ART_EMAIL = (string)objeto["ART_EMAIL"];
            ART_FECHA_CREACION = (DateTime)objeto["ART_FECHA_CREACION"];
            ART_CANT_INTEGRANTES = (int)objeto["ART_CANT_INTEGRANTES"];
        }

        public string ART_ID { get; set; }
        public string ART_NOMBRE { get; set; }
        public string ART_EMAIL { get; set; }
        public Nullable<System.DateTime> ART_FECHA_CREACION { get; set; }
        public Nullable<int> ART_CANT_INTEGRANTES { get; set; }
    }
}
